# Generated by Django 5.1 on 2024-09-06 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='books',
            new_name='mybooks',
        ),
    ]
